### ISSUE TITLE
解法部分沒辦法理解：freeCodeCamp- Basic JavaScript: Record Collection

### ISSUE THREAD

**Issue by Orow** [LukaHuang/Mento-AMA#1]
附上freeCodeCamp案例網址: 
https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/basic-javascript/record-collection
這個case在原有collection中各個object(註1)(這裡用id稱戶)內容去判斷是否新增value

- 網站內容描述
![image](https://user-images.githubusercontent.com/46784843/52908381-0f124800-32b0-11e9-9638-e84f7ce351d6.png)

- 完成此case所需條件
![image](https://user-images.githubusercontent.com/46784843/52908413-85af4580-32b0-11e9-8cc1-9452ae88c313.png)

其中get a hint的解法加上原始code如下
```js
// Setup
var collection = {
    "2548": {
      "album": "Slippery When Wet",
      "artist": "Bon Jovi",
      "tracks": [ 
        "Let It Rock", 
        "You Give Love a Bad Name" 
      ]
    },
    "2468": {
      "album": "1999",
      "artist": "Prince",
      "tracks": [ 
        "1999", 
        "Little Red Corvette" 
      ]
    },
    "1245": {
      "artist": "Robert Palmer",
      "tracks": [ ]
    },
    "5439": {
      "album": "ABBA Gold"
    }
};
// Keep a copy of the collection for tests
var collectionCopy = JSON.parse(JSON.stringify(collection));

// Only change code below this line
function updateRecords(id, prop, value) {
  if (prop === "tracks" && value !== "") {
   if(collection[id][prop]) {
    collection[id][prop].push(value);
   }
   else {
    collection[id][prop]=[value];
   }
  } else if (value !== "") {
    collection[id][prop] = value;

  } else {
    delete collection[id][prop];
  }
  
  return collection;
}

```

Q1.
---
網站中Get a hink解法裡面其中一個else無法理解為何如此寫(寫不到有什麼情況會進到這個else中)
圖片紅框處的的else不知道什麼情況下會執行到

![image](https://user-images.githubusercontent.com/46784843/52908272-619e3500-32ad-11e9-832e-5159f1a509c6.png)

我用結果來分析他為何這麼寫
=>把完成條件分別去執行function updateRecords(id, prop, value)

```js
if (prop === "tracks" && value !== "") {
   if(collection[id][prop]) {
    collection[id][prop].push(value);
   }
   else {
    collection[id][prop]=[value];
   }
....
```

從這邊看的話,if prop等於tracks跟value不為empty即進入迴圈後
=>”首先即遇到if(collection[id][prop])“
這一行不清楚有什麼判斷的效果會導致false而進到下一個else?

Q2.
---
完成必需的條件有一個如果value=""(empty)的話
=>prop should not be set,但解法都會跑到最後的else { collection[id][prop]}
```js
function updateRecords(id, prop, value) {
  if (prop === "tracks" && value !== "") {
   if(collection[id][prop]) {
    collection[id][prop].push(value);
   }
   else {
    collection[id][prop]=[value];
   }
  } else if (value !== "") {
    collection[id][prop] = value;

  } else {
    delete collection[id][prop];
  }
  
  return collection;
}

```
當條件if (prop === "tracks" && value !== "") 為false
=> else if (value !== "") 也為false的時候
=>執行delete collection[id][prop]
這邊的行為都會delete掉,但他完成所需條件是should not be set
是否有什麼我誤會的地方?

Q3.
---
註1:這裡var collection中的“2548","2468"這些是否稱為objects?還是就稱為string?

**Comment by LukaHuang** [comment]
這個問題有點太長，請試著拆成幾個小問題

**Comment by Orow** [comment]
修改後
上面為條件
下面接續3個問題

**Comment by Orow** [comment]
已理解
