### ISSUE TITLE
關於表單驗證作品問題

### ISSUE THREAD

**Issue by ChiangYuChi** [LukaHuang/Mento-AMA#10]
想請教您的兩個問題：
這是我上傳的網址
[https://chiangyuchi.github.io/](https://chiangyuchi.github.io/)

一、
目前index.html的表單檢測功能是正常運作的 ，（我把第二頁要檢測phone是否為空白的js程式碼先註解起來），但是第二頁無法操作同樣的檢測。

我用console.log檢查，出現 Uncaught TypeError: Cannot read property 'addEventListener' of null at all.js:19。它的意思是addEventListener監聽的事件不存在嗎？我能用同一個js檔案檢測不同頁面嗎？

二、
跳轉第二頁的功能，我用window.open，是不是能在同一頁直接跳下一頁，不要另開視窗？

**Comment by LukaHuang** [comment]
Q1: 程式有 Bug 喔，教你怎麼看，點擊錯誤的 js 
![image](https://user-images.githubusercontent.com/7014009/54928366-bdb04500-4f4e-11e9-8d48-e01d08f00ed5.png)

用 Chrome 開發工具可以看到哪邊寫錯，第二頁沒有 email 無法 addEventListener

![image](https://user-images.githubusercontent.com/7014009/54928485-ea645c80-4f4e-11e9-9ab5-36f866c512da.png)

Q2 - 你 Google 一下自己試試看吧

PS: 第一頁有 bug ，我輸入九位數密碼，都是數字，無法正常過關。
![image](https://user-images.githubusercontent.com/7014009/54927958-20eda780-4f4e-11e9-84ff-e641a00b5acc.png)

**Comment by ChiangYuChi** [comment]
我將第2頁的事件處理器在HTML。第一個問題已解決，謝謝。

所以是不是當要共用同樣的js功能時，例如第二頁也要操作相同的檢測動作時，
為了避免這樣的問題產生，或者用DOM事件處理，或者用HTML事件處理較好？

PS 第一頁的規則是最多8個字元，所以9位數不能過關 XD

**Comment by ChiangYuChi** [comment]
是我規則的英文寫錯 應該是Maximum 8 Characters 才對 XD

**Comment by codingluka** [comment]
> 我將第2頁的事件處理器在HTML。第一個問題已解決，謝謝。
> 
> 所以是不是當要共用同樣的js功能時，例如第二頁也要操作相同的檢測動作時，
> 為了避免這樣的問題產生，或者用DOM事件處理，或者用HTML事件處理較好？
> 
> PS 第一頁的規則是最多8個字元，所以9位數不能過關 XD

**Comment by LukaHuang** [comment]
> 是我規則的英文寫錯 應該是Maximum 8 Characters 才對 XD

一般來說都是最小八個字元比較合理喔，因為這樣密碼強度比較夠。

**Comment by LukaHuang** [comment]
> 我將第2頁的事件處理器在HTML。第一個問題已解決，謝謝。
> 
> 所以是不是當要共用同樣的js功能時，例如第二頁也要操作相同的檢測動作時，
> 為了避免這樣的問題產生，或者用DOM事件處理，或者用HTML事件處理較好？

檢測的 function 可以共用，但是綁定的物件是不同的。
參考一下知名套件的邏輯
https://github.com/jquery-validation/jquery-validation
