### ISSUE TITLE
the Conditional (Ternary) Operator案例疑問

### ISSUE THREAD

**Issue by Orow** [LukaHuang/Mento-AMA#2]
來源：https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/basic-javascript/use-the-conditional-ternary-operator

目的：
The syntax is:

condition ? statement-if-true : statement-if-false;

1. checkEqual should use the conditional operator
2. checkEqual(1, 2) should return false
3. checkEqual(1, 1) should return true
4. checkEqual(1, -1) should return false
```
code:
function checkEqual(a, b) {
  return a = b ? true : false;
}
```
這個結果在checkEqual(1, 2) , checkEqual(1,-1)會是true

後來 a = b 改為 a == b or a === b 
checkEqual(1, 2) , checkEqual(1,-1)就是true

請問一開始的 a = b 是只有判斷是不是同一type而不是判斷數值嗎？

**Comment by LukaHuang** [comment]
`a = b` 是給值，不是判斷，意思是把 b 的值丟給 a。
`a == b` or `a === b` 才是判斷式 (expression)。

**Comment by Orow** [comment]
了解
不過如果像freeCodeCamp自己hint上的解法

```js
function checkEqual(a, b) {
  return (a = b ? true : false );
}
```

checkEqual(1, 2);
在return後用小括號的話,這樣的a = b 還是給值嗎？

**Comment by LukaHuang** [comment]
沒錯，只要一個` = `就是給值，這在程式領域是通用但是初學者會覺得奇怪的部份，我一開始學也是疑惑很久。兩個等於 `==` 才是運算元(operator)，也就是`等於`的意思。

**Comment by Orow** [comment]
got it
受教了
