### ISSUE TITLE
Return值如何輸出function中key的字串?

### ISSUE THREAD

**Issue by Orow** [LukaHuang/Mento-AMA#3]
freeCodeCamp: https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/basic-javascript/word-blanks

```js
function wordBlanks(myNoun, myAdjective, myVerb, myAdverb) {
  // Your code below this line
  var result = "Bob's "+myAdjective+" "+myNoun+" "+myVerb+" "+myAdverb+"";
  // Your code above this line
  return result;
}

// Change the words here to test your function
wordBlanks("dog", "big", "ran", "quickly");
```

跑出來是這樣
`Bob's big dog ran quickly`

""中前後加入+符號可以顯示條件wordBlanks("dog", "big", "ran", "quickly")中的value是嗎？
這個叫做是什麼呢？

**Comment by LukaHuang** [comment]
這是一個典型的函式(function)，wordBlanks 的功用是要把輸入的四個值接起來，變成一串字。
內部實作你可以使用 + 號來連接字串。 

輸入 `wordBlanks("dog", "big", "ran", "quickly");` 輸出`dog big ran quickly`

我的解答給你參考，ps: 我沒完整看完題目，只有讓 test pass。

```js
function wordBlanks(myNoun, myAdjective, myVerb, myAdverb) {
  // Your code below this line
  var result = "";
  
  // Your code above this line
  return myNoun + " " + myAdjective + " " + myVerb + " " + myAdverb;
}
```

如果你想要排序的話制定一個規則，四個單字經過演算法會先進行排序再合併。
