### ISSUE TITLE
jQuery 事件處理 - on("click",function(){ 與 .click function(){  差別?

### ISSUE THREAD

**Issue by Orow** [LukaHuang/Mento-AMA#4]
想了解on("click",function(){ 與 .click function(){  差別?
有查到資料是說

> 一般沒有在一開始所綁定的就是只有已經生成的元素，如果你在**後來透過jquery或其他方式所增加的相同元素**都不會出現在這個事件所綁定的範圍裡，所以.click是沒有辦法幫助你做到動態的事件綁定\

> 這兩者間最大的差異，大概就在動態事件處理上，當然還有像是一些小差異像是

> .on()所佔用的記憶體會比.click還少

> .on()為Namespaced Events，可以做到事件命名的管理。

ref:  http://skaih.logdown.com/posts/712464-jquery-click-on-the-where-different

還有像是除了click外, change , keyup/down , mouse over/out在這邊也是相同概念嗎？

**Comment by LukaHuang** [comment]
別名(alias)的概念，看官方文件比較準
https://api.jquery.com/click/#click-handler
![image](https://user-images.githubusercontent.com/7014009/53236456-42e5d700-36cf-11e9-8a0c-4a92d8fa8822.png)

另外 jQuery 裡面有好幾種綁定事件的方式，比較推薦使用 on ，附上兩篇文章給你參考：

- [[译] Jquery中 .bind() .live() .delegate() 和 .on() 之间的区别]- (https://segmentfault.com/a/1190000010435530)
- [jQuery’s .bind() vs. .on()](https://stackoverflow.com/questions/11847021/jquery-s-bind-vs-on)

**Comment by Orow** [comment]
謝謝Luka建議與推薦文
