### ISSUE TITLE
jQuery選取第幾列的問題

### ISSUE THREAD

**Issue by Orow** [LukaHuang/Mento-AMA#5]
閱讀jQuerr達人的階梯一書看到選取不同列的疑問

如下
![image](https://user-images.githubusercontent.com/46784843/53321591-df002000-3913-11e9-898b-baec4c4610bd.png)
此例子是三列的個別hover效果不同
code:

```js
$(function(){
   // 
    var duration = 300;

    // buttons1 ----------------------------------------
    // buttons1  第一列
    $('#buttons1 button:nth-child(-n+4)')
        .on('mouseover', function() {
            $(this).stop(true).animate({
                backgroundColor: '#ae5e9b',
                color: '#fff'
            }, duration);
        })
        .on('mouseout', function(){
            $(this).stop(true).animate({
                backgroundColor: '#fff',
                color: '#ebc000'
            }, duration);
        });

    // buttons1  第二列
    $('#buttons1 button:nth-child(n+5):nth-child(-n+8)')
        .on('mouseover', function(){
            $(this).stop(true).animate({
                borderWidth: '12px',
                color: '#ae5e9b'
            }, duration, 'easeOutSine');
        })
        .on('mouseout', function(){
            $(this).stop(true).animate({
                borderWidth: '0px',
                color: '#ebc000'
            }, duration, 'easeOutSine');
        });

    // buttons1  第三列
    $('#buttons1 button:nth-child(n+9)')
        .on('mouseover', function(){
            $(this).find('> span')
                .stop(true).animate({width: '100%'}, duration, 'easeOutQuad');
        })
        .on('mouseout', function(){
            $(this).find('> span')
                .stop(true).animate({width: '0%'}, duration, 'easeOutQuad');
        });

});

```
不理解的部分是為什麼
第一列是nth-child(-n+4)
第二列是nth-child(n+5):nth-child(-n+8)
第三列是nth-child(n+9)

**Comment by LukaHuang** [comment]
請把程式碼上傳到Codepen。😬

**Comment by Orow** [comment]
codepen : https://codepen.io/Orow/pen/oVgxpy
這個例子中用codepen無法看到實際效果(他還有normalize.css 跟不同的js檔)
不過問題在怎麼選擇這三列進行修飾
不知html與js此兩樣程式碼是否足夠讓你確認

**Comment by LukaHuang** [comment]
js 檔案沒有正確的引入，請使用 CDN 解決之

**Comment by Orow** [comment]
已引入jQuery & jQuery UI

**Comment by LukaHuang** [comment]
好喔，範例已經可以執行。 
請看這一篇 
nth-child 選擇器有算數學的功用 
nth-child(an + b) 的時候，n 會從 0 開始計算
所以範例中選取第一行元素的語法 button:nth-child(-n+4)
第一個 n 是 0，對應的是 button:nth-child(-0 + 4)  等於 button:nth-child(4)
第二個 n 是  1，對應的是 button:nth-child(-1 + 4) 等於 button:nth-child(3)
第三個 n 是 2 ，對應的是 button:nth-child(-2 + 4) 等於 button:nth-child(2)
第四個 n 是 3 ，對應的是 button:nth-child(-3+ 4) 等於 button:nth-child(1)
其他以此類推

相關文章: [使用CSS3 :nth-child(n) 選取器教學](http://csscoke.com/2013/09/21/%E4%BD%BF%E7%94%A8css3-nth-childn-%E9%81%B8%E5%8F%96%E5%99%A8%E8%A9%B3%E8%A7%A3/)
