### ISSUE TITLE
.trigger('click', [true])中的true是代表什麼意思呢?

### ISSUE THREAD

**Issue by Orow** [LukaHuang/Mento-AMA#7]
在A的function中select到想選取的元素後,使用trigger執行click的事件,後面有一個[true],
ex. .trigger('click', [true])
不知道這個true代表的是什麼意思呢？

是當下A的function是true? 還是執行‘click’後的function()中是true(click function不為A)?
附上A function

```js
var current = 1;
    function autoScroll(){
        if(current == -1){
            return false;
        }
        $('#menu ul li a').eq(current%$('#menu ul li a').length).trigger('click',[true]);
        current++;
    }
```

完整code比較複雜,如果需要再附上來

**Comment by Orow** [comment]
```js
$('#menu ul li a').eq(current%$('#menu ul li a').length).trigger('click',[true])
= a[0].trigger('click',[true])
```

用chrome去確認這樣true代表的也是array(0)的意思？
![Screenshot at Mar 19 15-46-05](https://user-images.githubusercontent.com/46784843/54588842-fd62c280-4a5e-11e9-9b7c-4e52f4f3ccaf.png)

**Comment by LukaHuang** [comment]
一般來說只要懂用法即可，如果要深入了解的話需要看 jQuery 的 source code。
