### ISSUE TITLE
關於vue小作品問題

### ISSUE THREAD

**Issue by kylemocode** [LukaHuang/Mento-AMA#8]
1.第一次看到設計稿的時候發現用一個個component寫再組起來會很麻煩，所以最後還是先刻好版再用vue去動態改變內容，想請問什麼狀況下你會使用component的寫法呢？

2.關於computed計算屬性的用法。寫的過程發現有些function寫在method跟computed都能work,要怎麼判斷使用哪個更適合呢？

https://codepen.io/oldmo/pen/mojqYy?editors=1010

**Comment by LukaHuang** [comment]
1. 可以先全部做完再拆成 component，這樣比較直覺，用你覺得最順的方法做。如果 Component 需要重複使用且狀態較多的情況我會拆出來用。全部都使用 Component 則是訓練自己能夠開發中型的 Vuejs 專案。

2. computed 的資料不會依照 data 狀態更新而改變，method 則會。Computed 用起來感覺比較語意化。Method 泛用程度較高，之前我做一些即時的計算本來想用 Computed 做，但效果不如預期，就大部分都改成使用 Method 來實作。

這篇寫的不錯，請參考：
https://ithelp.ithome.com.tw/articles/10191808。
